### ISSUE TITLE
Add lines to show different doubling rates

### ISSUE THREAD

**Issue by basti12354** [jollyjinx/covid19-numbers#1]
Hi Patrick,
I check your graph and other graphs frequently. Sometimes I found graphs that are showing lines for different doubling rates (for exampling doubling every two days, every three days, every ten days...) which makes it easier to understand and to compare the graphs of different countries.

for example here: 
https://ourworldindata.org/grapher/covid-confirmed-cases-since-100th-case?time=0..67&country=DEU+ITA+ESP+CHE

**Comment by jollyjinx** [comment]
that's a great graph and wasn't aware of that kind of graph. I'll have a look if I can incorporate something like that

**Comment by jollyjinx** [comment]
hmmm using infections day1 / infections day2 would create something like that and one could draw the 3days lines at 1.26 and the like, but it's very jumpy. <img width="569" alt="image" src="https://user-images.githubusercontent.com/49925/77834762-502d8a80-7147-11ea-8684-4c11f9024d43.png">

**Comment by jollyjinx** [comment]
I've added the 2 , 7 , 14 day doubling lines now.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/49925/77879278-5a8c7900-725a-11ea-89fb-ce9d33ba3d11.png">
